import { title } from "process";

export const featuredProducts = [
  {
    id: 1,
    name: "Detox & Anti-inflammatory Tea",
    slug: "detox-anti-inflammatory-tea",
    title: "Natural Support for Digestive Wellness",
    description: "A soothing herbal tea blend crafted to support the body's natural cleansing processes while promoting overall wellness and vitality.'s natural detoxification process while promoting a healthy inflammatory response and overall wellness.",
    price: 35000,
    weight: "400g",
    image: "/products/detox.png",
    category: "Detox",
    keyBenefits: [
      "Supports natural detoxification",
      "Promotes daily wellness",
      "Encourages hydration",
      "Supports a healthy lifestyle",
    ],
  },
  {
    id: 2,
    name: "Female Corrective",
    slug: "female-corrective",
    title: "Natural Support for Women's Productive Wellness",
    description: "A botanical wellness blend designed to support hormonal balance, reproductive wellness, and overall female vitality.",
    price: 35000,
    weight: "450g",
    image: "/products/female.png",
    category: "Women's Health",
    keyBenefits: [
      "Supports women's wellness",
      "Promotes hormonal balance",
      "Encourages reproductive health",
      "Supports overall well-being",
    ],
    
  },
  {
    id: 3,
    name: "Liver Care",
    slug: "liver-care",
    title: "Natural Support for Liver Wellness and Detoxification",
    description: "A carefully crafted herbal blend designed to support liver function and the body's natural detoxification processes.",
    price: 40000,
    weight: "400g",
    image: "/products/livercare.png",
    category: "Liver Support",
    keyBenefits: [
      "Supports liver health",
      "Promotes natural cleaning",
      "Encourages digestive wellness",
      "Supports overall vitality",
    ],
  },
  {
    id: 4,
    name: "Gut Care",
    slug: "gut-care",
    title: "Natural Support for Digestive Wellness",
    description: "Developed to support healthy digestion, gut balance, and digestive comfort for everyday wellness.",
    price: 35000,
    weight: "400g",
    image: "/products/gutcare.png",
    category: "Digestive Health",
    keyBenefits: [
      "Supports digestive health",
      "Promotes gut balance",
      "Encourages digestive wellness",
      "Supports overall vitality",
    ],
  },
  {
    id: 5,
    name: "Gastritis Powder",
    slug: "gastritis-powder",
    title: "Natural Support for Digestive Wellness",
    description: "A soothing herbal tea blend crafted to support the body's natural cleansing processes while promoting overall wellness and vitality.",
    price: 35000,
    weight: "450g",
    image: "/products/gastritis.png",
    category: "Digestive Health",
    keyBenefits: [
      "Supports digestive health",
      "Promotes gut balance",
      "Encourages digestive wellness",
      "Supports overall vitality",
    ],
  },{
    id: 6,
    name: "Uterine Herbal Mix",
    slug: "uterine-herbal-mix",
    title: "Natural Support for Kidney & Urinary Wellness",
    description: "Our Kidney Care Formula is a botanical blend developed to support healthy kidney function, urinary wellness, and the body's natural cleansing processes.",
    price: 35000,
    weight: "400g",
    image: "/products/uterine.png",
    category: "Women's Health",
    keyBenefits: [
      "Supports kidney wellness",
      "Promotes urinary tract health",
      "Encourages healthy hydration",
      "Supports overall well-being",
    ],
    
  },
];


